import { useState } from 'react';
import { Pause, Play, ArrowUp } from 'lucide-react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { Action, Brand, BrandMark, Chapter, Reveal } from './Brand';

const faqs = [
  ['¿Tengo que cambiar las herramientas que ya uso?', 'No. La idea de VIDERE es partir de los datos que ya tenés: las exportaciones de tu CRM, los usuarios de tu web y tus pedidos. En esta demo usamos tres archivos de ejemplo para mostrarte cómo funciona, sin conectar tus sistemas reales.'],
  ['¿La demo está usando inteligencia artificial?', 'No. Esta demo corre completamente en tu navegador y usa coincidencias entre correos para conectar datos ficticios. Las cuatro respuestas se calculan sobre esos datos. El motor del proyecto contempla Claude para razonar sobre casos ambiguos y traducir preguntas a cálculos verificables.'],
  ['¿Necesito saber programar?', 'Para explorar la demo, no. Está hecha para quien conoce su negocio, no para un equipo técnico. Si solicitás acceso, podremos entender qué datos usás y acompañarte con los próximos pasos del producto.'],
  ['¿Qué pasa con mis datos?', 'La demo no sube archivos ni envía los datos de ejemplo a una IA. Solo recuerda tu decisión de unión en este navegador; podés borrarla con “Reiniciar”. Si solicitás acceso, guardamos los datos del formulario para contactarte sobre VIDERE.'],
];

export const EditorialMarquee = () => {
  const [paused, setPaused] = useState(false);
  return <div className="editorial-marquee" data-testid="editorial-marquee"><div className={`marquee-track ${paused ? 'paused' : ''}`} aria-hidden="true">{[0, 1, 2, 3].map(i => <span className="marquee-item" key={i}>Ver el todo.<span className="marquee-symbol">✳</span><em>Entender las partes.</em><span className="marquee-symbol">✳</span></span>)}</div><button className="marquee-control" onClick={() => setPaused(!paused)} aria-label={paused ? 'Reanudar movimiento' : 'Pausar movimiento'} data-testid="marquee-pause-button">{paused ? <Play size={12} /> : <Pause size={12} />}</button></div>;
};

export const FAQ = () => <section className="faq-section page-width section-space" data-testid="faq-section"><Reveal><Chapter number="04" id="faq-chapter">POR SI TE LO ESTABAS PREGUNTANDO</Chapter><h2 className="section-title" data-testid="faq-title">Todo claro.<br /><em>Desde el principio.</em></h2></Reveal><Reveal className="faq-list"><Accordion type="single" collapsible>{faqs.map(([question, answer], i) => <AccordionItem value={`faq-${i}`} key={question}><AccordionTrigger data-testid={`faq-question-${i}`}>{question}</AccordionTrigger><AccordionContent data-testid={`faq-answer-${i}`}>{answer}</AccordionContent></AccordionItem>)}</Accordion></Reveal></section>;

export const Closing = ({ onAccess, onPrivacy }) => <footer className="footer" data-testid="site-footer"><div className="page-width"><Reveal className="closing-cta"><div><span className="eyebrow" data-testid="closing-eyebrow"><span className="status-dot" /> EL PRÓXIMO PASO ES VERLO</span><h2 data-testid="closing-title">Tu negocio, <em>en perspectiva.</em></h2><p data-testid="closing-description">Dejá de juntar piezas. Empezá a ver el todo.</p></div><Action id="footer-access-button" onClick={onAccess}>Solicitar acceso a VIDERE</Action></Reveal><div className="footer-links"><Brand footer /><span className="footer-definition" data-testid="footer-definition">Del latín <em>vidēre</em>. Ver, comprender.</span><a data-testid="footer-demo-link" href="#demo">Explorar la demo ↗</a><button data-testid="footer-privacy-button" onClick={onPrivacy}>Privacidad</button></div><div className="footer-wordmark" aria-hidden="true"><span>videre</span><BrandMark /></div><div className="footer-bottom"><span data-testid="copyright">© {new Date().getFullYear()} VIDERE</span><span data-testid="footer-tagline">MENOS RUIDO. MÁS CLARIDAD.</span><a href="#inicio" data-testid="back-to-top-link">Volver arriba <ArrowUp size={13} /></a></div></div></footer>;