import { ShieldCheck, Fingerprint, ScanEye } from 'lucide-react';
import { Reveal, Chapter } from './Brand';

const principles = [
  { icon: ScanEye, title: 'Si hay una duda, la ves.', text: 'Una coincidencia no siempre es una certeza. Los datos que se contradicen se señalan, no se esconden.', number: '01' },
  { icon: Fingerprint, title: 'Cada respuesta deja una huella.', text: 'No alcanza con tener un número. Tenés que poder entender de dónde salió y qué datos lo sostienen.', number: '02' },
  { icon: ShieldCheck, title: 'Tu negocio. Tus reglas.', text: 'Un motor pensado para usar tu propia clave de IA, con permisos por rol y decisiones que quedan registradas.', number: '03' },
];

export const Trust = () => <section className="trust-section page-width section-space" id="confianza" data-testid="trust-section"><Reveal><Chapter number="03" id="trust-chapter">LA CONFIANZA NO ES UNA CAJA NEGRA</Chapter></Reveal><div className="trust-grid"><Reveal className="trust-image-wrap"><img src="https://images.unsplash.com/photo-1569258592171-357ea26da4df?auto=format&fit=crop&w=1000&q=85" alt="Estructura de hormigón geométrica iluminada por luz natural" loading="lazy" className="trust-image" /><div className="trust-image-grain" /><div className="trust-image-caption" data-testid="trust-image-caption"><span>OTRA PERSPECTIVA.</span><p>La diferencia<br />está en <em>ver.</em></p><span>VIDERE / VER CON CLARIDAD</span></div><div className="photo-cross">+</div></Reveal><div className="trust-copy"><Reveal><h2 className="section-title" data-testid="trust-title">Inteligencia, sí.<br /><em>A ciegas, nunca.</em></h2><p className="trust-intro" data-testid="trust-description">Porque tomar una decisión importante no debería ser un acto de fe.</p></Reveal><div className="trust-principles">{principles.map(({ title, text, number, icon: Icon }, i) => <Reveal delay={i * .08} className="trust-principle" key={number}><span className="principle-number">{number}</span><div><h3 data-testid={`trust-principle-title-${i}`}>{title}</h3><p data-testid={`trust-principle-description-${i}`}>{text}</p></div><Icon size={21} strokeWidth={1.25} /></Reveal>)}</div></div></div></section>;